### ISSUE TITLE
giveGold() Not Working

### ISSUE THREAD

**Issue by RhinoCodes** [glixzzy/blooket-wrapper#11]
Hello, I was inegrating the give gold feature into a project, i joined a game I found using your pin-finder (it was gold quest), ran it an got 
`node:238) UnhandledPromiseRejectionWarning: Error: e does not exist in the game!
    at /home/runner/pog-champ-blooket/node_modules/blooket/src/Blooket.js:568:23
    at Array.forEach (<anonymous>)
    at Blooket.giveGold (/home/runner/pog-champ-blooket/node_modules/blooket/src/Blooket.js:566:15)`

Any idea what's going on?

**Comment by Greenlio** [comment]
Hello, from the error you gave, quite obviously, a player named "e" is not in the Blooket game that you provided a pin for.

**Comment by RhinoCodes** [comment]
@Greenlio Yes I'm not dumb, I saw that. But i had a tab open with 'e' in the game. And when I ran getGameData() with the game pin e was in the game. Sorry for not providing more info!

**Comment by glixzzy** [comment]
Hello, thanks for letting me know about this issue.

This issue might be fixed in the v2, I'm currently rewriting this code.

**Comment by RhinoCodes** [comment]
Np! Is v2 going to be on a dev branch so people can help out?

**Comment by glixzzy** [comment]
Fixed the bug and v2 is released !!

**Comment by donaldli2020** [comment]
woohoo!
