### ISSUE TITLE
Add more control to started games

### ISSUE THREAD

**Issue by mollthecoder** [glixzzy/blooket-wrapper#14]
When we create a game using ``client.createGame`` we should be able to do basic things to interact with it, such as detecting when players join, being able to kick players, and being able to start the game. It'd also be nice to be able to change how much time/units are needed to end the game.

**Comment by gimmy74** [comment]
We need more control on the whole wrapper 💀

**Comment by mollthecoder** [comment]
> We need more control on the whole wrapper 💀

There's only so much that can be done using the raw API alone. It's been 3 days with no response, so I'll go off to create my own wrapper. It will utilize more than just the raw API, allowing it to be much more controllable.

**Comment by mollthecoder** [comment]
If you'd like, I can message you when I publicize it.

**Comment by gimmy74** [comment]
> If you'd like, I can message you when I publicize it.

you got discord?

**Comment by Greenlio** [comment]
@mollthecoder @gimmy74 Yes- gliz doesn't check this repository as they have better things to handle (check their blooket-hack repository).

Instead of instantly jumping to conclusions, I'd like wait lol.

**Comment by glixzzy** [comment]
> > We need more control on the whole wrapper 💀
> 
> 
> 
> There's only so much that can be done using the raw API alone. It's been 3 days with no response, so I'll go off to create my own wrapper. It will utilize more than just the raw API, allowing it to be much more controllable.

I've been out that's why I didn't reply but yeah I can try and add this in the next version.
