### ISSUE TITLE
getAnswers() should be easier to parse

### ISSUE THREAD

**Issue by themysticsavages** [glixzzy/blooket-wrapper#15]
I know this is an easy fix, but `getAnswers()` shouldn't return neat strings, but arrays, like this:
```js
[['question1', 'answer1'], ['question2', 'answer2']]
```

**Comment by Greenlio** [comment]
or just like .forEach it..

**Comment by themysticsavages** [comment]
> or just like .forEach it..

This is what I mean:
```js
const data = [];

response.data.questions.forEach(quetsion => {
            data.push("Question: " + quetsion.question + " | Answer: " + quetsion.correctAnswers)
});
```
Unless if it's for a CLI or something

**Comment by Greenlio** [comment]
just use the example lol

**Comment by themysticsavages** [comment]
bruh, what if you just want the question or just the answer? you have to find some strange way to split the string to get only the values

**Comment by themysticsavages** [comment]
never mind from other issues i see, the creator of this repo will probably never go to this issue

**Comment by Greenlio** [comment]
nah, they'll get to this issue. now that you close it, they definitely won't. He created this thinking about developers, for non developers just use the blooket hack repo lol

**Comment by Greenlio** [comment]
i agree it's cool to separate it but you can split the string at | if you really want that

**Comment by themysticsavages** [comment]
ok then

**Comment by glixzzy** [comment]
I agree, I'll change it in the next version. I haven't been working on this wrapper a lot because I don't know what to add.
