### ISSUE TITLE
Chrome extension not working

### ISSUE THREAD

**Issue by cph101** [glixzzy/blooket-wrapper#22]
Hello,

First of all, great API! I use it for my iOS shortcut [”500 Blooket Tokens”](https://github.com/cph101/500-Blooket-Tokens).

I have a chrome extension which I think uses this API [(mynameismax/blooket-extension)](https://github.com/mynameismax/blooket-extension). Upon checking, I noticed that Glixzzy is a contributor to this extension. The in-game hacks work fine for me, but all the Global hacks except “Spoof Blooks” don’t work.

I would greatly appreciate it if Glixzzy could fix this bug.

Many thanks,
C

**Comment by glixzzy** [comment]
The blooket extension was deprecated after a couple days of it being released my and a friend made it. This person reposted it and I'm pretty sure my friend told them to take it down.

**Comment by cph101** [comment]
Thanks! Would it be possible to incorporate the spoof Blooks on the Blooks page into your hack too? (I know you can already join games with it)

**Comment by cph101** [comment]
Hi again!

Would it be OK with you if I developed this extension further?

I’m considering these changes:
- [x] Adding support for Safari
- [x] Updating some of the Global cheats

**Comment by glixzzy** [comment]
> Hi again!
> 
> Would it be OK with you if I developed this extension further?
> 
> I’m considering these changes:
> 
> * [x]  Adding support for Safari
> * [x]  Updating some of the Global cheats

For further questions you can join my discord and dm me their, https://glizzezrs.xyz/discord and I'll have to ask my friend who made the extension with me about this.
