### ISSUE TITLE
API Endpoints changed

### ISSUE THREAD

**Issue by mmccall0813** [glixzzy/blooket-wrapper#24]
API endpoints have changed, and some other stuff might've too. I tried to update to the new endpoints by just changing the urls, but Blooket must have changed more than that, as I still dont show up in a game when trying to join.

**Comment by mmccall0813** [comment]
Yes, they are easy to find in the Network tab. But I changed the api links the new ones in the source, and it still doesn't work.

**Comment by glixzzy** [comment]
Yeah a lot has changed! 

I'm too focused on fixing/making this https://github.com/glixzzy/blooket-hack I don't have time for this wrapper anymore, sorry.
