### ISSUE TITLE
Request to remove package tag

### ISSUE THREAD

**Issue by RedYetiDev** [glixzzy/blooket-wrapper#8]
Hello @glixzzy,

On your NPM package for this project, one of the keywords you are using is the exact name of my archived blooket package [(blooket.js)](https://github.com/redyetidev/blooket.js). This may be a coincidence, but I would like to request you do not use the "blooket.js" tag, as it seems like you are marketing off of my failure. Legally, you don't **need** to remove the tag, but I do request you do. If this is a coincidence, I apologize for accusing you.

Thank you for understanding,
@RedYetiDev

**Comment by glixzzy** [comment]
Hello, I didn't actually intend to take it from your project. Although I'd like to keep it for SEO.

**Comment by RedYetiDev** [comment]
Oh, I am very sorry for accusing you. Sorry to bother you.
